### ISSUE TITLE
Does not handle PB&J

### ISSUE THREAD

**Issue by millerti** [mkuipers/is_it_a_sandwich#3]
PB&J scores 75%, probably because it's OK to each jelly with your hands. Credit to Cyrus for hunting down this bug.

**Comment by mkuipers** [comment]
Jelly is weird to eat with your hands.

**Comment by millerti** [comment]
Jelly is popular to eat with your hands. See pop culture, including https://www.youtube.com/watch?v=QvDbzb_gItI
